---
title: "Model_v1"
author: "Zi Yang"
date: "2021/4/7"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Process county death data

```{r}
Sys.setlocale("LC_TIME", "English")
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(cowplot)
covid<-read_xlsx("D:/Study/CMU/Statistical Practice/EDA/bmodel/COVID_CASES_OH_CNTY_20210223_pop.xlsx")
covid$DATE<-as.Date(covid$DATE,"%m/%d/%Y")
death<-covid%>%
  filter(DATE<=as.Date("2021-01-01") 
                      & DATE>=as.Date("2020-08-01"))%>%
  select(COUNTY,DATE,NEWDEATHS,CUMDEATHS)%>%
  mutate(Log_Newdeath=log(NEWDEATHS+1),
         Log_Cumdeath=log(CUMDEATHS+1))

county_name<-as.vector(distinct(death,COUNTY)[-c(63,81),])
```


## ADAMS County Test

```{r}
allen<-death%>%filter(COUNTY=="ADAMS")
spline.allen<-smooth.spline(x = allen$DATE, y = allen$Log_Newdeath)
ggplot(data=allen)+geom_point(aes(x=DATE,y=Log_Newdeath))+
  geom_line(aes(x=as.Date(spline.allen$x,origin="1970-01-01"),y=spline.allen$y))+
  theme_bw()
```

## County data and spline

```{r,out.width="50%",fig.height=8}
for(i in 1:22){
  county1<-death%>%filter(COUNTY==county_name$COUNTY[(i-1)*4+1])
  county2<-death%>%filter(COUNTY==county_name$COUNTY[(i-1)*4+2])
  county3<-death%>%filter(COUNTY==county_name$COUNTY[(i-1)*4+3])
  county4<-death%>%filter(COUNTY==county_name$COUNTY[(i-1)*4+4])
  spline1<-smooth.spline(x = county1$DATE, y = county1$Log_Newdeath)
  spline2<-smooth.spline(x = county2$DATE, y = county2$Log_Newdeath)
  spline3<-smooth.spline(x = county3$DATE, y = county3$Log_Newdeath)
  spline4<-smooth.spline(x = county4$DATE, y = county4$Log_Newdeath)
  p1<-ggplot(data=county1)+geom_point(aes(x=DATE,y=Log_Newdeath))+
  geom_line(aes(x=as.Date(spline1$x,origin="1970-01-01"),y=spline1$y))+
  theme_bw()+labs(title=county_name$COUNTY[(i-1)*4+1])
  p2<-ggplot(data=county2)+geom_point(aes(x=DATE,y=Log_Newdeath))+
  geom_line(aes(x=as.Date(spline2$x,origin="1970-01-01"),y=spline2$y))+
  theme_bw()+labs(title=county_name$COUNTY[(i-1)*4+2])
  p3<-ggplot(data=county3)+geom_point(aes(x=DATE,y=Log_Newdeath))+
  geom_line(aes(x=as.Date(spline3$x,origin="1970-01-01"),y=spline3$y))+
  theme_bw()+labs(title=county_name$COUNTY[(i-1)*4+3])
  p4<-ggplot(data=county4)+geom_point(aes(x=DATE,y=Log_Newdeath))+
  geom_line(aes(x=as.Date(spline4$x,origin="1970-01-01"),y=spline4$y))+
  theme_bw()+labs(title=county_name$COUNTY[(i-1)*4+4])
  print(plot_grid(p1, p2,ncol = 1, nrow = 2))
  print(plot_grid(p3, p4,ncol = 1, nrow = 2))
}
```

## Calculation of spline slope for the start of the semester

```{r}
spline_slope_start<-c()
for(i in 1:88){
  county.data<-death%>%filter(COUNTY==county_name$COUNTY[i])
  spline<-smooth.spline(x = county.data$DATE, 
                        y = county.data$Log_Newdeath)
  # Not sure whether we can calculate through this way
  slope.start<-spline$y[27]-spline$y[26]
  spline_slope_start<-c(spline_slope_start,slope.start)
}

spline_slop<-data.frame(
  COUNTY=county_name,
  spline_slop_start=round(spline_slope_start,4)
)
head(spline_slop,15)
```




