---
title: "Time series analysis with updated window definition"
author: "Cheyenne Ehman"
date: "3/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Select varible of interests

```{r}
## If you don't have the covidcast package, run following line
#devtools::install_github("cmu-delphi/covidcast", ref = "main", subdir = "R-packages/covidcast",dependencies = T)
```



```{r message=FALSE, warning=FALSE}
source("step2_data_wrangle.R")
################### school reopen dates ################### 
district_policies <- OH_K12 %>%
  distinct(county,county_enroll,leaid,district_enroll,schooltemporaryshutdown,opendategrouped,teachingmethod)
# Calculate the proportion and generate date brackets
major_opendate <- district_policies%>%
  filter(!schooltemporaryshutdown %in% c('Closed indefinitely','Pending','Unknown'))%>%
  group_by(county,county_enroll,opendategrouped)%>%
  summarise(n_opendate = sum(district_enroll))%>% # number of students under certain date for each county
  mutate(prop_opendate = round(n_opendate/county_enroll,2))%>% # proportion
  group_by(county)%>%
  #filter(prop_opendate>0.6)%>% 
  slice(which.max(prop_opendate))%>% # filter large proportions of students with same reopen dates #can be replaced with # slice(which.max(prop_opendate))#
  mutate(reopen_3w_after = opendategrouped + 21)%>%
  select(-n_opendate)
```


```{r}
require(lubridate)
opendate_cases <- case_mobility%>%
  inner_join(major_opendate,by=c('COUNTY'='county'))%>%
  group_by(COUNTY)%>%
  filter(DATE>=reopen_3w_after - 56 & DATE<= as.Date('2020-12-25'))%>%
  ungroup()%>%
  mutate(window_id = case_when(
    DATE <= reopen_3w_after~"2month_before_3wafteropen",
    reopen_3w_after<DATE & DATE<=reopen_3w_after+ 56~"2month_after_3wafteropen",
    TRUE ~ 'Other'))%>%
  mutate(death_prop_1000 = round(CUMDEATHS/POPULATION,5)*1000,
         window_id = as.factor(window_id))%>%
  left_join(wide_teaching_enroll,by=c('COUNTY'='county','county_enroll'))
# select the start date and end date data for each window of time
  
death_incident_window <- opendate_cases%>%
  group_by(COUNTY,window_id)%>%
  arrange(DATE)%>%
  mutate(avg_work_7d = mean(work_prop_7d,na.rm = T), avg_res_visit = mean(res_visit_prop,na.rm = T),avg_bar_visit = mean(bar_visit_prop,na.rm = T) )%>%
  filter(row_number()==1 | row_number()==n())%>%
  mutate(death_incident = diff(CUMDEATHS),death_incident_per_1000 = diff(CUMDEATHS)*1000/POPULATION)%>%
  distinct(COUNTY,POPULATION,avg_work_7d,avg_res_visit,avg_bar_visit,Online_Only,On_Premises,Hybrid,death_incident,death_incident_per_1000,window_id)
```


```{r}
y1y0 <- death_incident_window %>%
  filter(window_id!='Other')%>%
  group_by(COUNTY)%>%
  mutate(y1= death_incident_per_1000, y0 = lag(death_incident_per_1000,n=1))%>%
  arrange(COUNTY)%>%
  drop_na(y0) 
 
#hist(y1y0$y1,main = "Histogram of Death Incidents per 1000", xlab = "y1")
ggplot(y1y0, aes(x = y1)) + 
  geom_histogram(bins = 10, fill = "salmon") + 
  theme_bw() + 
  labs(x = "Y1", y = "Frequency",
       title = "Marginal Distribution of Y1")
ggplot(y1y0, aes(x = log(y1))) + 
  geom_histogram(bins = 10, fill = "salmon") + 
  theme_bw() + 
  labs(x = "Y1", y = "Frequency",
       title = "Marginal Distribution of log(Y1)")
#hist(y1y0$y0,main = "Histogram of Death Incidents per 1000", xlab = "y0")
ggplot(y1y0, aes(x = y0)) + 
  geom_histogram(bins = 15, fill = "salmon") + 
  theme_bw() + 
  labs(x = "Y1", y = "Frequency",
       title = "Marginal Distribution of Y0")
ggplot(y1y0, aes(x = log(y0))) + 
  geom_histogram(bins = 15, fill = "salmon") + 
  theme_bw() + 
  labs(x = "Y1", y = "Frequency",
       title = "Marginal Distribution of log(Y0)")
```

# Y1 on Y0

```{r}
summary(lm(y1~y0,data = y1y0))
# NOT SIGNIFICANT
```

# Y1 on X = teaching method and Y0

```{r}
# on teaching method alone
#summary(lm(y1~Hybrid,data = y1y0))
#summary(lm(y1~On_Premises,data = y1y0))
#summary(aov(y1~Online_Only,data = y1y0))
#summary(lm(y1~y0+Hybrid,data = y1y0))
#summary(lm(y1~y0+On_Premises,data = y1y0))
#summary(lm(y1~y0+Online_Only,data = y1y0))
```


# Y1 on Mobility Measures and Y0

```{r}
# NONE SIGNIFICANT
summary(lm(y1~avg_work_7d,na.action='na.omit',data = y1y0)) # SIGNIFICANT
#summary(lm(y1~avg_res_visit,na.action='na.omit',data = y1y0))
#summary(lm(y1~avg_bar_visit,na.action='na.omit',data = y1y0))
summary(lm(y1~y0+avg_work_7d,na.action='na.omit',data = y1y0)) # WORK SIGNIFICANT
#summary(lm(y1~y0+avg_res_visit,na.action='na.omit',data = y1y0))
#summary(lm(y1~y0+avg_bar_visit,na.action='na.omit',data = y1y0))
```

# Y1 on all confounders

```{r}
# NONE SIGNIFICANT
summary(lm(y1~y0+avg_work_7d+Online_Only,na.action='na.omit',data = y1y0))
```

# Correlation

```{r}
corr_data<-y1y0%>%select(POPULATION,On_Premises,Online_Only,
                         avg_work_7d,avg_res_visit,y1)
corr_data<-corr_data[,-1]
corr_data$POPULATION<-log(corr_data$POPULATION)
cor(na.omit(corr_data))
names(corr_data)[1]<-"Log Pop"

corrplot(cor(na.omit(corr_data)),type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```
```{r}
ggplot(data=y1y0)+
  geom_point(aes(x=On_Premises,y=y1,col="On Premises"))+
  geom_smooth(method = "lm",aes(x=On_Premises,y=y1,col="On Premises"))+
  geom_point(aes(x=Online_Only,y=y1,col="Online Only"))+
  geom_smooth(method = "lm",aes(x=Online_Only,y=y1,col="Online Only"))+
  xlab("Proportion")+
  theme_bw()+labs(col="Teaching Method")+theme(legend.position="bottom")
```

```{r}
library("PerformanceAnalytics")
chart.Correlation(data.frame(y1=y1y0$y1,On_Premises=y1y0$On_Premises,
                             Online_Only=y1y0$Online_Only))
chart.Correlation(data.frame(On_Premises=y1y0$On_Premises,
                             Online_Only=y1y0$Online_Only,
                             Work=y1y0$avg_work_7d,
                             Restaurant=y1y0$avg_res_visit,
                             Log_Pop=log(y1y0$POPULATION)))
chart.Correlation(data.frame(y1=y1y0$y1,
                             Work=y1y0$avg_work_7d,
                             Restaurant=y1y0$avg_res_visit,
                             Log_Pop=log(y1y0$POPULATION)))
```

```{r}
# library
library(ggridges)
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
```

```{r}
# Plot
options(scipen=10000)


state_open_teaching_enroll%>%
  filter(teachingmethod %in% c("On Premises","Hybrid"))%>%
  ggplot(aes(y=opendate_teaching_county_enroll/1000, x=opendate,  fill=teachingmethod)) +
  geom_bar(,position = 'stack', stat = 'identity',width = 3) +
  geom_rect(data = state_open_teaching_enroll[1,],
            aes(xmin = as.Date('2020/08/26'), 
                xmax = as.Date('2020/12/15'), ymin=-Inf, ymax=Inf), 
            color = NA, alpha = 0.2, show.legend = F, fill = 'orange') +
  labs(x='School Reopen Date',y = 'County Student Enrollment / 1000',title = 'Number of Student Enrollment on Different School Reopen Dates \n(On Premises & Hybrid)',col="",fill="Majority Teaching Method")+ xlim(as.Date('2020/08/01'),as.Date('2021/01/01'))+
  scale_fill_manual(values = c("#00BA38", "#F8766D")) +
  theme_bw()+theme(legend.position= c(0.77, 0.8),legend.title = element_text(size=13),legend.text = element_text(size=13),axis.title = element_text(size=15),axis.text = element_text(size=15),legend.background = element_rect(fill = alpha("orange",0.0)),legend.key.size = unit(1.4,"lines"),title = element_text(size=12.9))


state_open_teaching_enroll%>%
  filter(teachingmethod %in% c("On Premises","Hybrid"))%>%
  ggplot(aes(y=opendate_teaching_state_prop, x=opendate,  fill=teachingmethod)) +
  geom_bar(,position = 'stack', stat = 'identity',width = 3) +ylim(0,1)+
  geom_rect(data = state_open_teaching_enroll[1,],
            aes(xmin = as.Date('2020/08/26'), 
                xmax = as.Date('2020/12/15'), ymin=-Inf, ymax=Inf), 
            color = NA, alpha = 0.2, show.legend = F, fill = 'orange') +
  labs(x='School Reopen Date',y = 'County Student Propotion',title = 'Percentage of Student on Different School Reopen Dates \n(On Premises & Hybrid)',col="",fill="Majority Teaching Method")+ xlim(as.Date('2020/08/01'),as.Date('2021/01/01'))+
  scale_fill_manual(values = c("#00BA38", "#F8766D")) +
  theme_bw()+theme(legend.position= c(0.77, 0.8),legend.title = element_text(size=13),legend.text = element_text(size=13),axis.title = element_text(size=15),axis.text = element_text(size=15),legend.background = element_rect(fill = alpha("orange",0.0)),legend.key.size = unit(1.4,"lines"),title = element_text(size=12.9))

```



