---
title: "Time series analysis"
author: "Cheyenne Ehman"
date: "3/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("step2_data_wrangle.R")
```

# Select varible of interests

```{r}
################### school reopen dates ################### 
district_policies <- OH_K12 %>%
  distinct(county,county_enroll,leaid,district_enroll,schooltemporaryshutdown,opendategrouped,teachingmethod)
```

# Calculate the proportion and generate date brackets

```{r}
prop_opendate <- district_policies%>%
  filter(!schooltemporaryshutdown %in% c('Closed indefinitely','Pending','Unknown'))%>%
  group_by(county,county_enroll,opendategrouped)%>%
  summarise(n_opendate = sum(district_enroll))%>% # number of students under certain date for each county
  mutate(prop_opendate = round(n_opendate/county_enroll,2))%>% # proportion
  group_by(county)%>%
  #filter(prop_opendate>0.6)%>% 
  slice(which.max(prop_opendate))%>% # filter large proportions of students with same reopen dates #can be replaced with # slice(which.max(prop_opendate))#
  mutate(threeweeks_before = opendategrouped-21,sixweeks_later = as.Date('2020-12-15')+42)%>%
  select(-n_opendate)
```

```{r}
opendate_cases <- cases%>%
  inner_join(prop_opendate,by=c('COUNTY'='county'))%>%
  group_by(COUNTY)%>%
  filter(DATE>=threeweeks_before & DATE<=sixweeks_later)%>%
  group_by(COUNTY)%>%
  mutate(window_id = case_when(DATE<opendategrouped~"3 weeks before reopen",
    DATE>=opendategrouped & DATE<'2020-12-15' ~'fall semester',
    DATE>='2020-12-15' & DATE< as.Date('2020-12-15')+21 ~ '3 weeks after end',
    DATE>=as.Date('2020-12-15')+21 ~ '6 weeks after end'
  ))%>%
  select(-STATE,-STUSAB,-ST_LAT,-ST_LONG,-STATEFP,-GNISID,-UID,-CODE3)%>%
  mutate(death_prop = round(CUMDEATHS/POPULATION,5),
         window_id = as.factor(window_id))%>%
  left_join(wide_teaching_enroll,by=c('COUNTY'='county','county_enroll'))
# select the start date and end date data for each window of time
  
start_end_window <- opendate_cases%>%
  group_by(COUNTY,window_id)%>%
  arrange(DATE)%>%
  filter(row_number()==1 | row_number()==n())%>%
  arrange(COUNTY,DATE)%>%
  group_by(COUNTY,window_id)%>%
  mutate(y_labels = ifelse(row_number()==1,'y0','y1'))%>%
  dcast(COUNTY+POPULATION+county_enroll+opendategrouped+threeweeks_before+sixweeks_later+Online_Only+Hybrid+On_Premises+window_id+major_teaching~y_labels,value.var = 'CUMDEATHS')
```


```{r}
start_end_window$window_id <- factor(start_end_window$window_id,
         levels = c("3 weeks before reopen",
         "fall semester",
         "3 weeks after end",
         "6 weeks after end"))
start_end_window$major_teaching <- factor(start_end_window$major_teaching,
         levels = c("On Premises",
         "Hybrid",
         "Online Only"))

start_end_window %>%
  #filter(window_id == "3 weeks before reopen") %>%
  mutate(death_prop_y0 = y0/POPULATION) %>%
  ggplot(aes(y = death_prop_y0, 
             fill = major_teaching))+ 
  geom_boxplot(na.rm = T) +
  facet_grid(~window_id)+ 
  theme_bw()+ 
  labs(y = "Death Proportion",
       fill = "Majority Teaching Method",
       title = "Death Proportion")

#ggsave("Deathprop_box.jpg", width = 8.5, height = 5)

require(scales)
start_end_window %>%
  #filter(window_id == "3 weeks before reopen") %>%
  mutate(death_prop_inc = (y1 - y0)/POPULATION) %>%
  ggplot(aes(y = death_prop_inc, 
             fill = major_teaching))+ 
  geom_boxplot(na.rm = T) +
  facet_grid(~window_id) + 
  theme_bw()+ 
  labs(y = "Death Proportion",
       fill = "Majority Teaching Method",
       title = "Death Proportion Increase") + 
  scale_y_continuous(labels = comma)
#ggsave("Deathpropinc_box.jpg", width = 8.5, height = 5)
```

```{r}
start_end_window %>%
  filter(window_id == "fall semester") %>%
  mutate(death_prop_inc = (y1 - y0)/POPULATION) %>%
  ggplot(aes(x = Online_Only, y = death_prop_inc, color = major_teaching)) + 
  geom_point()+ 
  theme_bw() + 
  labs(x = "Proportion of Students learning Remote",
       y = "Death Proportion Increase",
       title = "Y1 against X1",
       subtitle = "During Fall Semester",
       color = "Majority Teaching Method")

ggsave("y1x1.jpg", width = 7, height = 5)
```


```{r}
county_policy_wide$major_teaching <- factor(county_policy_wide$major_teaching,
         levels = c("On Premises",
         "Hybrid",
         "Online Only"))
# see when the intesection happens
date.intercept <- as.Date("2020-11-24")

# add 95% confidence bans
confidence_level <- .95
z_cl <- qnorm(confidence_level)


cases %>%
  left_join(county_policy_wide[,c("county","major_teaching")],
            by = c("COUNTY" = "county")) %>%
  na.omit() %>%
  group_by(DATE, major_teaching) %>%
  summarise(total_deaths = sum(CUMDEATHS),
            total_pop = sum(POPULATION),
            death_prop = total_deaths/total_pop,
            death_prop_upper = death_prop + z_cl*sqrt(death_prop*(1 - death_prop)/total_pop),
            death_prop_lower = death_prop - z_cl*sqrt(death_prop*(1 - death_prop)/total_pop),
            .groups = "drop") %>%
  ggplot(aes(x = DATE, y = death_prop, group = major_teaching))+
    geom_rect(data=opendate_cases[1,],
            aes(xmin=as.Date("2020/08/26"), xmax=as.Date("2020/12/12"),
                ymin=-Inf,ymax=Inf),
            color = NA,alpha=0.2, show.legend = F, fill = "orange") + 
    geom_line(aes(color = major_teaching),size = 1, alpha = .8) + 
    geom_ribbon(aes(ymin = death_prop_lower, ymax = death_prop_upper,
                    fill= major_teaching), 
                alpha = .3, show.legend = F)+ 
    geom_vline(xintercept = date.intercept, linetype = "dashed") + 
    annotate("text",x = date.intercept,y = .001,
             label = date.intercept,
             hjust = 1.1) + 
    theme_bw() + 
    labs(x = "Date", y = "Total Death Proportion", 
         title = "Total Death Proportion by Teaching Method",
         subtitle = "Red area represents the fall semester",
         color = "Majority Teaching Method")

# +
#   scale_x_date(date_breaks = "2 month", date_labels = "%b-%y")
```


```{r}
lag_cases <- cases %>%
  left_join(county_policy_wide[,c("county","major_teaching")],
            by = c("COUNTY" = "county")) %>%
  na.omit()%>%
  select(COUNTY,DATE,CUMDEATHS,POPULATION,major_teaching)%>%
  group_by(COUNTY) %>%
  mutate(lag_total_deaths = lag(CUMDEATHS,21)) %>%
  ungroup()%>%
  group_by(DATE,major_teaching) %>%
  summarise(total_deaths = sum(CUMDEATHS),
            total_deaths_lag = sum(lag_total_deaths),
            total_pop = sum(POPULATION),
            death_prop = total_deaths/total_pop,
            lag_death_prop = total_deaths_lag/total_pop,
            death_prop_inc = (total_deaths-total_deaths_lag)/total_pop,
            .groups = "drop")

ggplot(lag_cases, aes(x = lag_death_prop, y = death_prop, color = major_teaching)) + 
    geom_line(size = 1,alpha = .8, na.rm=T)+ 
  theme_bw() + 
  labs(x = "Death Proportion of 3 weeks prior", y  = "Death Proportion",
       color = "Majority Teaching Method")
```

```{r}
peak.date <- as.Date("2020-12-23")
ggplot(lag_cases,aes(x = DATE, y = death_prop_inc, 
                     color = major_teaching,
                     fill = "red")) + 
    geom_line(na.rm = T) +
    geom_rect(data = lag_cases[1,],
            aes(xmin=as.Date("2020/08/26"), xmax=as.Date("2020/12/12"),
                ymin=-Inf,ymax=Inf),
            color = NA,alpha=0.2, show.legend = F) + 
    geom_vline(xintercept = peak.date, linetype = "dashed")+ 
    annotate("text",x = peak.date,y = .0005,
             label = peak.date,
             hjust = 1.2)  + 
  theme_bw() + 
  labs(x = "Date",
       y = "Death Proportion Increase", 
       title = "Death Proportion Increase by Teaching Method",
       subtitle = "Increase compared to 3 Week Lag \nRed area represents Fall Semester",
       color = "Majority Teaching Method") + 
  scale_y_continuous(labels = comma)
```


